rosamakinen/webserv

.gitignore
src/main.cpp

Initial version of setting up a socket and listening to requests

Add main code for the first iteration

---

src/Server.cpp

Instead of doing `iterator < vector.end()` we shold've been doing `iterator != vector.end()`, so fixed that. Also added some consts there as we are just copying values from one vector to the other, not changing them.

Fix iterator looping

---

.gitignore
include/Socket.hpp
src/Socket.cpp
src/main.cpp

Not fully functional yet but now answers with this default string

Make socket nonblocking

---

include/Socket.hpp
src/Socket.cpp
src/main.cpp

Also clean up on every aisle and tried to move some of the socket code to the socket. Everything on main at the moment looks like server managers code now :) also added. setsockopt call so that we can now bind multiple sockets to the same port, which I believe is a possible configuration.

Make socket nonblocking by using poll() instead of select

---

Makefile
config/default.conf
include/ExceptionHandler.hpp
include/Exceptions.hpp
include/HttpResponse.hpp
include/Server.hpp
include/Socket.hpp
include/WebServer.hpp
src/ConfigParser.cpp
src/ExceptionHandler.cpp
src/HttpResponse.cpp
src/Server.cpp
src/Socket.cpp
src/main.cpp

We now have a base class for all exception that happen when handling clients: Exception, so all exceptions that lead us to respond to a client with somekind of Bad Request HttpResponse should inherit from that class. The ExceptionHandler will take care of all these and so we just add the response statuses there when we want to add new "bad request" exceptions.
There is also now a try catch block in the main function that basically catches any other exceptions so when there is a seg fault, configuration file invalid or whatever you can now just throw and that block will take care of it.

Exception handling base

---

Makefile
include/HttpRequest.hpp
include/HttpRequestParser.hpp
include/HttpResponse.hpp
include/HttpResponseParser.hpp
include/ScalarConverter.hpp
include/WebServer.hpp
src/HttpRequest.cpp
src/HttpRequestParser.cpp
src/HttpResponse.cpp
src/HttpResponseParser.cpp
src/ScalarConverter.cpp
src/main.cpp

Added a converter for string to int float and double and from int to string (example to how to use it in HttpResponseParser). Already merged with @rosamakinen s branch currently in PR so should be okay to merge once that one goes out!

String to int

---

include/WebServer.hpp
src/HttpResponse.cpp

There was probably some merge issues as there was build errors due to missing includes. Note to self but also to all of us: let's make sure that always when pushing something to main / creating a pull request that the project builds and works. All existing functionality should work as before the newest changes unless specifically agreed otherwise :) !

Add missing includes

---

src/Server.cpp

hey ladies!
sorry about the delay, i think these changes should allow you to spin up a server by hand while i can keep working on the config parser.
i'm getting a build error on the scalar converter stuff from meri, but i don't see why these additions shouldn't be just fine.
i'll be "available" over the break. so feel free to pester me.

adding explicit server method to split from the confic mess

---

include/Exceptions.hpp
include/Socket.hpp
include/WebServer.hpp
src/HttpResponse.cpp
src/Socket.cpp
src/main.cpp

Added exceptions here and made sure we close the connection if the client does too

Fix penging client request issue

---

config/default.conf
include/Server.hpp
include/WebServer.hpp
src/Server.cpp

reworked server class

---

include/HttpRequestParser.hpp
src/main.cpp

switched some functions to private in HttpServerParser

---

Makefile
include/Exceptions.hpp
include/FileHandler.hpp
public_www/index.html
src/FileHandler.cpp
src/Socket.cpp
src/main.cpp

File handler reads the relative path and returns a string represetning the content of the file. Tested and locally run, works!

Add html file converter

---

Makefile
include/Exceptions.hpp
include/FileHandler.hpp
include/HttpResponse.hpp
public_www/cgi_bin/hello_world.py
public_www/error_pages/500.html
public_www/index.html
src/FileHandler.cpp
src/HttpResponse.cpp
src/Socket.cpp
src/main.cpp

Added parsing to the http response as well as semi dynamic python form! DO NOT MERGE BEFORE https://github.com/rosamakinen/webserv/pull/38

Add cgi base

---

Makefile
include/HttpRequest.hpp
include/HttpRequestParser.hpp
include/WebServer.hpp
src/HttpRequest.cpp
src/HttpRequestParser.cpp
src/main.cpp

restructured the main loop logic for request parsing, to make it more adaptable in the future, if need be

New request loop

---

Makefile
include/Exceptions.hpp
include/FileHandler.hpp
include/HttpRequestHandler.hpp
include/HttpRequestParser.hpp
include/HttpResponse.hpp
include/HttpResponseParser.hpp
include/Timer.hpp
include/WebServer.hpp
src/ExceptionManager.cpp
src/FileHandler.cpp
src/HttpRequestHandler.cpp
src/HttpRequestParser.cpp
src/HttpResponse.cpp
src/Timer.cpp
src/main.cpp

Added headers to makefile as well

Request handler draft

---

Makefile
include/Client.hpp
include/HttpRequestHandler.hpp
include/HttpRequestParser.hpp
include/HttpResponseParser.hpp
include/Server.hpp
include/Socket.hpp
public_www/cgi-bin/download_file.py
public_www/cgi-bin/hello_world.py
public_www/index.html
src/Client.cpp
src/HttpRequestHandler.cpp
src/HttpRequestParser.cpp
src/HttpResponseParser.cpp
src/Server.cpp
src/Socket.cpp
src/main.cpp

next up, mocing the code to server class or smt + adding multiple reading for clients that input bigger requests

Added a wrapper for incoming requests and outgoing responses to separately handle POLLIN and POLLOUT

---

config/danTest.conf
config/good/default.conf
include/FileHandler.hpp
include/HttpRequest.hpp
include/HttpRequestHandler.hpp
include/HttpRequestParser.hpp
include/HttpResponse.hpp
include/WebServer.hpp
src/FileHandler.cpp
src/HttpRequest.cpp
src/HttpRequestHandler.cpp
src/HttpRequestParser.cpp
src/HttpResponse.cpp
src/ServerHandler.cpp

Configurations should have>
location ending with a '/'
directory ending with a '/'
-> request has the resourcepath, directory and location etc.

Refactor httprequestparser

---

src/HttpRequest.cpp
src/HttpRequestParser.cpp

parseHttpRequest was most of the issue. put inside a catch block and delete the request when it fails. it rethrows the same error it received.

leak caught

---

client_tests_webserv.json
curl_tests
include/Client.hpp
include/HttpRequest.hpp
include/HttpRequestHandler.hpp
include/HttpRequestParser.hpp
include/HttpResponse.hpp
include/ServerHandler.hpp
include/WebServer.hpp
src/CgiHandler.cpp
src/Client.cpp
src/FileHandler.cpp
src/HttpRequest.cpp
src/HttpRequestHandler.cpp
src/HttpRequestParser.cpp
src/HttpResponse.cpp
src/ServerHandler.cpp
webserv.json

Handling the chunking now.. HttpResponse has some changes too as it needed to be more flexibl too.. there is stil the issue of keeping a connection open to specific client etc, which is where I will continue to next.

Handle chunking

---

config/danTest.conf
include/CgiHandler.hpp
include/Exceptions.hpp
include/FileHandler.hpp
include/HttpRequestParser.hpp
include/Server.hpp
include/WebServer.hpp
public_www/error_pages/413.html
src/ConfigParser.cpp
src/ExceptionManager.cpp
src/HttpRequestParser.cpp
src/Server.cpp
webserv.json

i'll show you a max_body.
i updated thunder, since there's not an index1.html anymore it expects a 404.

81 enforce max body and give default name to server name
